### Get Follow-Up with both Meeting and Questionnaire by token
GET http://localhost:3000/api/v1/followups/1234567

###
### Get Follow-Up with only Questionnaire by token
GET http://localhost:3000/api/v1/followups/7654321
###
### Get Follow-Up with only Meeting by token
GET http://localhost:3000/api/v1/followups/987654321
###
### Get Follow-Up with invalid token
GET http://localhost:3000/api/v1/followups/invalidtoken
###
### Submit Follow-Up with both Meeting and Questionnaire by token
PUT http://localhost:3000/api/v1/followups/1234567
Content-Type: application/json

{
  "subject": "Follow-Up Meeting",
  "emailText": "<html><body>Thank you for your time. Please fill out the questionnaire and select a time slot for our meeting. <a href='http://localhost:5173/followup/1234567' target='_blank'>Click here</a> to access the follow-up form.</body></html>",
  "selectedTimeSlot": {
    "startTime": "2023-10-01T10:00:00Z",
    "endTime": "2023-10-01T11:00:00Z"
  },
  "questions": [
    {
      "question": "What is your name?",
      "hasRange": false,
      "hasSentence": true,
      "studentAnswer": "John Doe"
    }
  ]
}
###
### Submit Follow-Up with only Questionnaire
PUT http://localhost:3000/api/v1/followups/7654321
Content-Type: application/json

{
  "subject": "Follow-Up Meeting",
  "emailText": "<html><body>Thank you for your time. Please fill out the questionnaire. <a href='http://localhost:5173/followup/7654321' target='_blank'>Click here</a> to access the follow-up form.</body></html>",
  "questions": [
    {
      "question": "What is your name?",
      "hasRange": false,
      "hasSentence": true,
      "studentAnswer": "John Doe"
    }
  ]
}
###
### Submit Follow-Up with only Meeting by token
PUT http://localhost:3000/api/v1/followups/987654321
Content-Type: application/json

{
  "subject": "Follow-Up Meeting",
  "emailText": "<html><body>Thank you for your time. Please select a time slot for our meeting. <a href='http://localhost:5173/followup/987654321' target='_blank'>Click here</a> to access the follow-up form.</body></html>",
  "selectedTimeSlot": {
    "startTime": "2023-10-01T10:00:00Z",
    "endTime": "2023-10-01T11:00:00Z"
  }
}
###
### Submit Follow-Up with invalid token by token
PUT http://localhost:3000/api/v1/followups/invalidtoken
Content-Type: application/json

{
  "subject": "Follow-Up Meeting",
  "emailText": "<html><body>Thank you for your time. Please fill out the questionnaire and select a time slot for our meeting. <a href='http://localhost:5173/followup/1234567' target='_blank'>Click here</a> to access the follow-up form.</body></html>",
  "selectedTimeSlot": {
    "startTime": "2023-10-01T10:00:00Z",
    "endTime": "2023-10-01T11:00:00Z"
  },
  "questions": [
    {
      "question": "What is your name?",
      "hasRange": false,
      "hasSentence": true,
      "studentAnswer": "John Doe"
    }
  ]
}
###
###