POST http://localhost:3000/teachers/students/6772a92116a8203a0f4ec461/questionnaires
Content-Type: application/json

{
  "title": "Questionnaire 1",
  "token": "123456",
  "questions": [
    {
      "title": "Question 1",
      "description": "This is a question",
      "type": "text"
    },
    {
      "title": "Question 2",
      "description": "This is a question",
      "type": "text"
    }
  ]
}