POST http://localhost:3000/register
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "phone": "123-456-7890",
  "gmail": "chayimdeutsch@gmail.com"
}

###
POST http://localhost:3000/auth/check-approval
Content-Type: application/json

{
  "gmail": "chayimdeutsch@gmail.com"
}

###
POST http://localhost:3000/admin/chayimdeutsch@gmail.com/approve

###
GET  http://localhost:3000/auth/google

###
GET http://localhost:3000/test

###
GET http://localhost:3000/admin/users

###
POST http://localhost:3000/admin/template
Content-Type: application/json

{
  "title": "First Template",
  "description": "This is the first template",
  "questions": [
    {
      "question": "What is your name?",
      "hasRange": false,
      "hasSentence": true
    },
    {
      "question": "What is your birthday?",
      "hasRange": false,
      "hasSentence": true
    },
    {
      "question": "From 1-10, how happy are you?",
      "hasRange": true,
      "hasSentence": false,
      "range": {
        "min": 1,
        "max": 10
      }
    },
    {
      "question": "What is your favorite color?",
      "hasRange": false,
      "hasSentence": false
    }
  ]
}

###
POST http://localhost:3000/chayimdeutsch@gmail.com/students
Content-Type: application/json

{
  "firstName": "First",
  "lastName": "Student",
  "phone": "123-456-7890",
  "gmail": "firstStudent@first.com",
  "followUpEmails": [
    {
      "scheduledDate": "2025-06-01"
    },
    {
      "scheduledDate": "2025-06-02"
    },
    {
      "scheduledDate": "2025-06-03"
    }
  ]
}

###
POST http://localhost:3000/admin/check-admin

Content-Type: application/json

{
  "gmail": "core.torah.followup@gmail.com"
}

###
POST http://localhost:3000/admin/check-admin