POST http://localhost:3000/register
Content-Type: application/json

{
  "firstName": "Toby",
  "lastName": "Deutsch",
  "phone": "123-456-7890",
  "gmail": "tobysdeutsch@gmail.com"
}

###
POST http://localhost:3000/auth/check-approval
Content-Type: application/json

{
  "gmail": "chayimdeutsch@gmail.com"
}

###
POST http://localhost:3000/admin/chayimdeutsch@gmail.com/approve

###
GET  http://localhost:3000/auth/google

###
GET http://localhost:3000/test

###
GET http://localhost:3000/admin/users

###
POST http://localhost:3000/teachers/students
Content-Type: application/json

{
  "firstName": "First",
  "lastName": "Student",
  "phone": "123-456-7890",
  "gmail": "firstStudent@first.com",
  "followUpEmails": [
    {
      "scheduledDate": "2025-06-01"
    },
    {
      "scheduledDate": "2025-06-02"
    },
    {
      "scheduledDate": "2025-06-03"
    }
  ]
}

###
POST http://localhost:3000/admin/check-admin

Content-Type: application/json

{
  "gmail": "core.torah.followup@gmail.com"
}

###
POST http://localhost:3000/admin/check-admin