### Register Hayim Deutsch
POST http://localhost:3000/api/v1/register
Content-Type: application/json

{
  "firstName": "Hayim",
  "lastName": "Deutsch",
  "phone": "123-456-7890",
  "gmail": "chayimdeutsch@gmail.com"
}

###
### Register Core
POST http://localhost:3000/api/v1/register
Content-Type: application/json

{
  "firstName": "Core",
  "lastName": "Torah",
  "phone": "123-456-7890",
  "gmail": "core.torah.followup@gmail.com"
}

###
### Create unapproved user 1
POST http://localhost:3000/api/v1/register
Content-Type: application/json

{
  "firstName": "Unapproved",
  "lastName": "User1",
  "phone": "123-456-7890",
  "gmail": "unapprovedUser1@gmail.com"
}

###
### Create unapproved user 2
POST http://localhost:3000/api/v1/register
Content-Type: application/json

{
  "firstName": "Unapproved",
  "lastName": "User2",
  "phone": "123-456-7890",
  "gmail": "unapprovedUser2@gmail"
}
###
### Check Approval of Approved User
POST http://localhost:3000/api/v1/auth/check-approval
Content-Type: application/json

{
  "gmail": "chayimdeutsch@gmail.com"
}

###
### Check Approval of Unapproved User
POST http://localhost:3000/api/v1/auth/check-approval
Content-Type: application/json

{
  "gmail": "unapprovedUser@gmail.com"
}

###
### See what returns from google auth
GET  http://localhost:3000/api/v1/auth/google

###
### Test Route
GET http://localhost:3000/api/v1/test

###
###