### Check Approval of Approved User
POST http://ec2-16-170-45-41.eu-north-1.compute.amazonaws.com:80/api/v1/auth/check-approval
Content-Type: application/json

{
  "email": "chayimdeutsch@gmail.com"
}

###
### Check Approval of Unapproved User
POST http://ec2-16-170-45-41.eu-north-1.compute.amazonaws.com:80/api/v1/auth/check-approval
Content-Type: application/json

{
  "email": "unapprovedUser@gmail.com"
}

###
### See what returns from google auth
GET  http://ec2-16-170-45-41.eu-north-1.compute.amazonaws.com:80/api/v1/auth/google

###
### Get User
GET http://ec2-16-170-45-41.eu-north-1.compute.amazonaws.com:80/api/v1/auth/user

# Response when using mock authentification
# {
#   "_id": "6770fcdb70be6909c4932583",
#   "email": "chayimdeutsch@gmail.com",
#   "googleId": "113882388930598865430"
# }