### Create Student First
POST http://ec2-16-170-45-41.eu-north-1.compute.amazonaws.com:80/api/v1/students
Content-Type: application/json

{
  "firstName": "First",
  "lastName": "Student",
  "phone": "123-456-7890",
  "email": "firstStudent@first.com",
  "eventDate": "2025-06-01",
  "scheduledEmails": [
    {
      "scheduledDate": "2025-06-01"
    },
    {
      "scheduledDate": "2025-06-02"
    },
    {
      "scheduledDate": "2025-06-03"
    }
  ]
}

# Response
# HTTP/1.1 201 Created
# {
#   "firstName": "First",
#   "lastName": "Student",
#   "email": "firstStudent@first.com",
#   "eventDate": "2025-06-01T00:00:00.000Z",
#   "teacher": "677e5992cc047516b454a80a",
#   "followUps": [],
#   "scheduledEmails": [
#     {
#       "scheduledDate": "2025-06-01T00:00:00.000Z",
#       "status": "pending",
#       "retryCount": 0,
#       "_id": "6787c6b1eee3b37873c22d30"
#     },
#     {
#       "scheduledDate": "2025-06-02T00:00:00.000Z",
#       "status": "pending",
#       "retryCount": 0,
#       "_id": "6787c6b1eee3b37873c22d31"
#     },
#     {
#       "scheduledDate": "2025-06-03T00:00:00.000Z",
#       "status": "pending",
#       "retryCount": 0,
#       "_id": "6787c6b1eee3b37873c22d32"
#     }
#   ],
#   "_id": "6787c6b1eee3b37873c22d2f",
#   "__v": 0
# }


###
### Create Hayim Student
POST http://ec2-16-170-45-41.eu-north-1.compute.amazonaws.com:80/api/v1/students
Content-Type: application/json

{
  "firstName": "Hayim",
  "lastName": "Student",
  "phone": "123-456-7890",
  "email": "chayimdeutsch@gmail.com",
  "eventDate": "2025-06-01",
  "scheduledEmails": [
    {
      "scheduledDate": "2025-06-01"
    }
  ]
}

###
### Create Student Second
POST http://ec2-16-170-45-41.eu-north-1.compute.amazonaws.com:80/api/v1/students
Content-Type: application/json

{
  "firstName": "Second",
  "lastName": "Student",
  "phone": "123-456-7890",
  "email": "secondStudent@second.com",
  "eventDate": "2025-06-01",
  "scheduledEmails": [
    {
      "scheduledDate": "2025-06-01"
    },
    {
      "scheduledDate": "2025-06-02"
    },
    {
      "scheduledDate": "2025-06-03"
    }
  ]
}

# Response
# HTTP/1.1 201 Created
# {
#   "firstName": "Second",
#   "lastName": "Student",
#   "email": "secondStudent@second.com",
#   "eventDate": "2025-06-01T00:00:00.000Z",
#   "teacher": "677e5992cc047516b454a80a",
#   "followUps": [],
#   "scheduledEmails": [
#     {
#       "scheduledDate": "2025-06-01T00:00:00.000Z",
#       "status": "pending",
#       "retryCount": 0,
#       "_id": "678800d2854eec19cc83279d"
#     },
#     {
#       "scheduledDate": "2025-06-02T00:00:00.000Z",
#       "status": "pending",
#       "retryCount": 0,
#       "_id": "678800d2854eec19cc83279e"
#     },
#     {
#       "scheduledDate": "2025-06-03T00:00:00.000Z",
#       "status": "pending",
#       "retryCount": 0,
#       "_id": "678800d2854eec19cc83279f"
#     }
#   ],
#   "_id": "678800d2854eec19cc83279c",
#   "__v": 0
# }

###
### Get Students
GET http://ec2-16-170-45-41.eu-north-1.compute.amazonaws.com:80/api/v1/students

# Response
# HTTP/1.1 200 OK
# [
#   {
#     "_id": "6787ff73673d5a06e3e0b595",
#     "firstName": "First",
#     "lastName": "Student",
#     "email": "firstStudent@first.com",
#     "eventDate": "2025-06-01T00:00:00.000Z",
#     "teacher": "677e5992cc047516b454a80a",
#     "followUps": [],
#     "scheduledEmails": [
#       {
#         "scheduledDate": "2025-06-01T00:00:00.000Z",
#         "status": "pending",
#         "retryCount": 0,
#         "_id": "6787ff73673d5a06e3e0b596"
#       },
#       {
#         "scheduledDate": "2025-06-02T00:00:00.000Z",
#         "status": "pending",
#         "retryCount": 0,
#         "_id": "6787ff73673d5a06e3e0b597"
#       },
#       {
#         "scheduledDate": "2025-06-03T00:00:00.000Z",
#         "status": "pending",
#         "retryCount": 0,
#         "_id": "6787ff73673d5a06e3e0b598"
#       }
#     ],
#     "__v": 0
#   },
#   {
#     "_id": "6787ff7b673d5a06e3e0b59d",
#     "firstName": "Hayim",
#     "lastName": "Student",
#     "email": "chayimdeutsch@gmail.com",
#     "eventDate": "2025-06-01T00:00:00.000Z",
#     "teacher": "677e5992cc047516b454a80a",
#     "followUps": [],
#     "scheduledEmails": [
#       {
#         "scheduledDate": "2025-06-01T00:00:00.000Z",
#         "status": "pending",
#         "retryCount": 0,
#         "_id": "6787ff7b673d5a06e3e0b59e"
#       }
#     ],
#     "__v": 0
#   }
# ]

###
### Get First Student By ID
GET http://ec2-16-170-45-41.eu-north-1.compute.amazonaws.com:80/api/v1/students/67896526dbfd25f355091bcf

# Response
# HTTP/1.1 200 OK
# {
#   "_id": "6787ff73673d5a06e3e0b595",
#   "firstName": "First",
#   "lastName": "Student",
#   "email": "firstStudent@first.com",
#   "eventDate": "2025-06-01T00:00:00.000Z",
#   "teacher": {
#     "_id": "677e5992cc047516b454a80a",
#     "firstName": "Hayim",
#     "lastName": "Deutsch",
#     "email": "chayimdeutsch@gmail.com",
#     "phone": "123-456-7890"
#   },
#   "followUps": [],
#   "scheduledEmails": [
#     {
#       "scheduledDate": "2025-06-01T00:00:00.000Z",
#       "status": "pending",
#       "retryCount": 0,
#       "_id": "6787ff73673d5a06e3e0b596"
#     },
#     {
#       "scheduledDate": "2025-06-02T00:00:00.000Z",
#       "status": "pending",
#       "retryCount": 0,
#       "_id": "6787ff73673d5a06e3e0b597"
#     },
#     {
#       "scheduledDate": "2025-06-03T00:00:00.000Z",
#       "status": "pending",
#       "retryCount": 0,
#       "_id": "6787ff73673d5a06e3e0b598"
#     }
#   ],
#   "__v": 0
# }

###
### Get Hayim Student By ID
GET http://ec2-16-170-45-41.eu-north-1.compute.amazonaws.com:80/api/v1/students/67896535dbfd25f355091bd7

# Response
# HTTP/1.1 200 OK
# {
#   "_id": "6787ff7b673d5a06e3e0b59d",
#   "firstName": "Hayim",
#   "lastName": "Student",
#   "email": "chayimdeutsch@gmail.com",
#   "eventDate": "2025-06-01T00:00:00.000Z",
#   "teacher": {
#     "_id": "677e5992cc047516b454a80a",
#     "firstName": "Hayim",
#     "lastName": "Deutsch",
#     "email": "chayimdeutsch@gmail.com",
#     "phone": "123-456-7890"
#   },
#   "followUps": [],
#   "scheduledEmails": [
#     {
#       "scheduledDate": "2025-06-01T00:00:00.000Z",
#       "status": "pending",
#       "retryCount": 0,
#       "_id": "6787ff7b673d5a06e3e0b59e"
#     }
#   ],
#   "__v": 0
# }

###
### Update Student First Emails
PUT http://ec2-16-170-45-41.eu-north-1.compute.amazonaws.com:80/api/v1/students/67896526dbfd25f355091bcf/emails
Content-Type: application/json

{
  "scheduledEmails": [
    {
      "scheduledDate": "2025-06-01"
    }
  ]
}

# Response
# HTTP/1.1 200 OK
# 
# {
#   "_id": "6787ff73673d5a06e3e0b595",
#   "firstName": "First",
#   "lastName": "Student",
#   "email": "firstStudent@first.com",
#   "eventDate": "2025-06-01T00:00:00.000Z",
#   "teacher": "677e5992cc047516b454a80a",
#   "followUps": [],
#   "scheduledEmails": [
#     {
#       "scheduledDate": "2025-06-01T00:00:00.000Z",
#       "status": "pending",
#       "retryCount": 0,
#       "_id": "678812d6d399d1735ac55453"
#     }
#   ],
#   "__v": 0
# }

###
### Update Non-Existent Student Emails
PUT http://ec2-16-170-45-41.eu-north-1.compute.amazonaws.com:80/api/v1/students/678800d2854eec19cc83279c/emails
Content-Type: application/json

{
  "scheduledEmails": [
    {
      "scheduledDate": "2025-06-01"
    }
  ]
}

# Response
# HTTP/1.1 404 Not Found
# {
#   "message": "Student not found"
# }

###
### Delete Student Second
DELETE http://ec2-16-170-45-41.eu-north-1.compute.amazonaws.com:80/api/v1/students/6789693825cbfe76a92c7be2

# Response
# HTTP/1.1 204 No Content

###
### Delete Non-Existent Student
DELETE http://ec2-16-170-45-41.eu-north-1.compute.amazonaws.com:80/api/v1/students/678800d2854eec19cc83279c

# Response
# HTTP/1.1 404 Not Found
# {
#   "message": "Student not found"
# }

###
